# Generated by Django 4.0.6 on 2022-12-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCardSectionsListMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopicCardSectionsListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.topiccardsectionslistmembermodel')),
            ],
        ),
        migrations.CreateModel(
            name='TopicCardSectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('t', 'text'), ('l', 'list')], max_length=10)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
                ('values', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.topiccardsectionslistmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TopicCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.topiccardsectionsmodel')),
            ],
        ),
    ]
