# Generated by Django 4.0.6 on 2022-12-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCardImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='topiccardmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='topiccardsectionslistmembermodel',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='topiccardsectionslistmodel',
            old_name='name',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='topiccardsectionslistmodel',
            old_name='values',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='topiccardsectionsmodel',
            old_name='values',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='topiccardsectionsmodel',
            old_name='value',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='topiccardmodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.topiccardimagemodel'),
        ),
    ]
