# Generated by Django 4.0.6 on 2022-12-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_itemmodel_testmodel_pagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tx', 'text'), ('g', 'gallery'), ('ta', 'table')], max_length=10)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SingleQuoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=10000)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.ManyToManyField(to='info.rowmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RenameField(
            model_name='pagemodel',
            old_name='name',
            new_name='big_name',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='about',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='spoilers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='under_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topiccardsectionsmodel',
            name='expandable',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='topiccardmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='topiccardmodel',
            name='image',
            field=models.ManyToManyField(blank=True, to='info.topiccardimagemodel'),
        ),
        migrations.RemoveField(
            model_name='topiccardmodel',
            name='info',
        ),
        migrations.AddField(
            model_name='topiccardmodel',
            name='info',
            field=models.ManyToManyField(blank=True, to='info.topiccardsectionsmodel'),
        ),
        migrations.AlterField(
            model_name='topiccardmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='topiccardsectionslistmodel',
            name='right',
        ),
        migrations.AddField(
            model_name='topiccardsectionslistmodel',
            name='right',
            field=models.ManyToManyField(to='info.topiccardsectionslistmembermodel'),
        ),
        migrations.RemoveField(
            model_name='topiccardsectionsmodel',
            name='list',
        ),
        migrations.AddField(
            model_name='topiccardsectionsmodel',
            name='list',
            field=models.ManyToManyField(blank=True, to='info.topiccardsectionslistmodel'),
        ),
        migrations.RenameModel(
            old_name='TopicCardImageModel',
            new_name='ImageModel',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='rowmodel',
            name='row',
            field=models.ManyToManyField(to='info.textmodel'),
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='quotes',
            field=models.ManyToManyField(to='info.singlequotemodel'),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='images',
            field=models.ManyToManyField(blank=True, to='info.imagemodel'),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.singlequotemodel'),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='sub_chapters',
            field=models.ManyToManyField(blank=True, to='info.chaptermodel'),
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.tablemodel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='chapter',
            field=models.ManyToManyField(blank=True, to='info.chaptermodel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.singlequotemodel'),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='quotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.quotemodel'),
        ),
    ]
