# Generated by Django 4.0.6 on 2022-12-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_chaptermodel_quotemodel_rowmodel_singlequotemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemodel',
            name='quotes',
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='info.quotemodel'),
        ),
    ]
