# Generated by Django 4.0.6 on 2022-12-23 13:59

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_pagemodel_quotes_pagemodel_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/andrei399/personal/material-wiki/backend/images')),
        ),
    ]
