# Generated by Django 4.0.6 on 2022-12-28 13:08

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_imagemodel_name_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=pathlib.PurePosixPath('/home/andrei399/personal/material-wiki/backend/images')),
        ),
    ]
