# Generated by Django 4.0.6 on 2022-12-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_pagemodel_slug_alter_imagemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemodel',
            name='under_construction',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='under_construction',
            field=models.BooleanField(default=False),
        ),
    ]
