# Generated by Django 4.0.6 on 2023-01-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_chaptermodel_number_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='under_construction',
            field=models.BooleanField(default=False),
        ),
    ]
