# Generated by Django 4.0.6 on 2023-01-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_pagemodel_under_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermodel',
            name='disclaimer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
