# Generated by Django 4.0.6 on 2023-01-10 07:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_chaptermodel_disclaimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemodel',
            name='under_construction',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
    ]
