# Generated by Django 4.0.6 on 2023-01-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_alter_imagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='RelatedWikiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.imagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.imagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HomePagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_sections', models.ManyToManyField(blank=True, related_name='left_sections', to='info.homepagesectionmodel')),
                ('related_wikis', models.ManyToManyField(blank=True, to='info.relatedwikimodel')),
                ('sections', models.ManyToManyField(to='info.homepagesectionmodel')),
                ('social_media', models.ManyToManyField(blank=True, to='info.socialmediamodel')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pages', models.ManyToManyField(blank=True, to='info.pagemodel')),
            ],
        ),
    ]
