# Generated by Django 4.0.6 on 2023-01-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_socialmediamodel_alter_imagemodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='links_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
