# Generated by Django 4.0.6 on 2023-01-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_imagemodel_links_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedwikimodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.imagemodel'),
        ),
    ]
