# Generated by Django 4.0.6 on 2023-01-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_relatedwikimodel_image'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='chaptermodel',
            order_with_respect_to='number',
        ),
    ]
