# Generated by Django 4.0.6 on 2023-01-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_alter_chaptermodel_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='chaptermodel',
            order_with_respect_to=None,
        ),
    ]
