# Generated by Django 4.0.6 on 2023-01-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_alter_chaptermodel_order_with_respect_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FooterSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('links', models.ManyToManyField(blank=True, to='info.footerlinkmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(blank=True, max_length=10000, null=True)),
                ('extra_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_img', to='info.imagemodel')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.imagemodel')),
                ('sections', models.ManyToManyField(blank=True, to='info.footersectionmodel')),
                ('socials', models.ManyToManyField(blank=True, to='info.socialmediamodel')),
            ],
        ),
    ]
