# Generated by Django 4.0.6 on 2023-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_footerlinkmodel_footersectionmodel_footermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesectionmodel',
            name='type',
            field=models.CharField(choices=[('p', 'page'), ('t', 'text'), ('rt', 'side_text'), ('rp', 'side_page')], default='p', max_length=10),
            preserve_default=False,
        ),
    ]
