# Generated by Django 4.0.6 on 2023-01-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_homepagesectionmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesectionmodel',
            name='type',
            field=models.CharField(choices=[('p', 'page'), ('t', 'text'), ('st', 'side_text'), ('sp', 'side_page')], max_length=10),
        ),
    ]
